version: '3.8'

services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: bancocred_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bancocred
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bancocred_network

  # Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bancocred_backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=bancocred
      - JWT_SECRET=super-secret-key
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - bancocred_network

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bancocred_frontend
    ports:
      - "5175:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - bancocred_network

  # Adminer (Gerenciador de Banco de Dados)
  adminer:
    image: adminer
    container_name: bancocred_adminer
    ports:
      - "8090:8080"
    depends_on:
      - db
    networks:
      - bancocred_network

volumes:
  postgres_data:

networks:
  bancocred_network:
    driver: bridge
