version: '3.8'

services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: bancocred_db_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - bancocred_network_prod

  # PgAdmin (Interface Gr√°fica do Banco)
  pgadmin:
    image: dpage/pgadmin4
    container_name: bancocred_pgadmin_prod
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@bancocred.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin1234}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - bancocred_network_prod

  # Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: bancocred_backend_prod
    restart: always
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - bancocred_network_prod

  # Frontend (React + Vite + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: bancocred_frontend_prod
    restart: always
    ports:
      - "${APP_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - bancocred_network_prod

volumes:
  postgres_data_prod:

networks:
  bancocred_network_prod:
    driver: bridge
